### PR TITLE
Version 1.2.0

### PR DESCRIPTION
**Pull request by MBuchalik**
Among others, this PR adds the following changes:
- Files in this repo are now linted using Prettier.
- The `package.json` in this repo now only includes the packages we need for development. Currently, this is only Prettier.
- There is now a separate config for React.
- All linter configs are much more strict than before.
- There is now a Changelog file to document the changes. Previously, all changes were documented in the "Releases" section on GitHub, but I believe that a separate Changelog file is easier to use (e.g. if you have cloned the repo locally)
- The Readme file is now much more detailed.

> Important: Before releasing version 1.2.0, we need to update the Changelog to include the date of the release.

### CODE REVIEW

**Comment by georg-schwarz** [comment]
@rhazn @joluj How is the react linter config compared to yours? I think we should try to have one shared config, shouldn't we?

**Comment by rhazn** [comment]
I don't know, what is the reason for using a custom react linting aside from the recommended react linter from create react app?

**Comment by MBuchalik** [comment]
> I don't know, what is the reason for using a custom react linting aside from the recommended react linter from create react app?

First of all, as you might have seen, I am building on top of the default CRA config. The default CRA config allows quite a lot of things that, from my point of view, should not be done when developing in React. A few examples:

- The default CRA config allows buttons without a "type" attibute. The problem: The "type" attribute defaults to "submit". Which is most likely not what you want.
- By default, developers are allowed to use various kinds of function component definitions. For example, you can write `function MyComponent(props)` or `const MyComponent = props => ...` or `const MyComponent = function(props)`. The new linter config enforces one consistent style.
- In React, to define state in your components, you use a pattern like `const [myState, setMyState] = React.useState(...)`. I added a rule that enforces proper naming of these variables, so that developers don't write sth like `const [foo, bar] = React.useState(...)`. This also helps find typos (e.g. `const [foo, setFo] = React.useState(...)`)
- I added a rule that disallows array indexes to be used as Keys, since this is most of the time pretty bad for the internal diffing algorithm and should only be done if there is really no other alternative.
- It is now not allowed to define components inside components.

And much more. I believe these rules fix many problems developers might accidentally run into.

**Comment by rhazn** [comment]
There you have some more details George, I don't think we need to review these rules one-by-one, right? In any case, we are using the jvalue config already for everything. So I might be missing something about having a shared config, but I agree and we do. Big picture I think our linting is way over the top but I am prepared to accept that as difference of opinion 😅 .

**Comment by georg-schwarz** [comment]
Thanks @MBuchalik for the explanations!

@rhazn no need to review one-by-one from my side.
My question somewhat aims at your last comment: would you commit to using the linter config in the hub as well? I want this to be a somewhat democratic process where everyone can contribute because there is no right and wrong IMO, but we need sth that works for everyone ;-)

**Comment by rhazn** [comment]
Yes of course, we/I already did this when I set up the initial projects. They all use the shared jvalue linting config, they all fail the CI builds on 1 warning, they all contain pre commit hooks so changed code is linted locally before it even gets pushed. This should just be a change in the config (I assume), not the process itself.

We can fight about specific rules down the line but the overall idea is good, yeah.

**Comment by MBuchalik** [comment]
As a side note: If there is a certain rule that always just gets in your way, e.g. the `react/destructuring-assignment` rule, then please simply send a PR to this repo. (You can also deactivate it in your per-project eslint config as described in the Readme file.)

Btw: I highly recommend using automatic fixing as described in the Readme file. Otherwise, the linter will indeed reduce your productivity.

**Comment by rhazn** [comment]
I think the only large issue left is aligning this with the other @jvalue namespaced packages into the same repo (either npm or private). Everything else already works fine for the hub.

**Comment by MBuchalik** [comment]
Hm what exactly is the issue? You mean having both private packages (hosted on the GitHub registry) and public ones (hosted on NPM)? We could introduce a new namespace like `@jvalue-public`. Or, I could explain in the Readme file that you have to use `npm install (something) --registry=https://registry.npmjs.org/` when using both public and private packages scoped to `@jvalue`

**Comment by rhazn** [comment]
Yeah, we talked about this before. There are easy ways to tell npm that a certain namespace is found on a specific repository but that does not work right now because the jvalue namespace is split over npm and the private github repo.

I see no reason to do anything but move this out of the jvalue namespace so everything can work automatically. But that is not related to this MR, just my gripe with the overall setup 😅 .

**Pull request merged**
